name: Executable Build

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Install 7zip (macOS)
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew update
          brew install sevenzip

      - name: Install 7zip (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt remove p7zip-full
          wget https://www.7-zip.org/a/7z2300-linux-x64.tar.xz
          tar -xf 7z2300-linux-x64.tar.xz
          sudo cp 7zz /usr/bin/7zz
          
      - name: Compressed Files (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          7z a -tzip -mx=9 -mm=LZMA -mfb=258 -mmt=on ./build/${{ runner.os }}.zip ./*

      - name: Compressed Files (Linux & macOS)
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
        run: |
          7zz a -tzip -mx=9 -mm=LZMA -mfb=258 -mmt=on ./build/${{ runner.os }}.zip ./*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: meg-${{ runner.os }}-x86_64
          path: |
            build/*.zip

  upload-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: build

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/**
