name: Executable Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      # Compilation
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: 'pip'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ccache (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt install -y ccache
          echo ccache -V

      - name: Build (Linux)
        if: ${{ runner.os == 'Linux' }}
        uses: Nuitka/Nuitka-Action@main
        with:
          script-name: main.py
          standalone: true
          onefile: false
          output-file: meg-linux-x86_64
          enable-plugins: upx
          include-module: apscheduler.triggers.date
          include-data-dir: config=config

      # Compressed Files
      - name: Install 7zip (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: |
          wget https://www.7-zip.org/a/7z2201-linux-x64.tar.xz
          tar -xf 7z2201-linux-x64.tar.xz
          sudo cp 7zz /usr/bin/7zz

      - name: Compressed Files (Linux & macOS)
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
        run: |
          7zz a -tzip -mx=9 -mm=LZMA -mfb=258 -mmt=on ./build/meg-${{ runner.os }}-x86_64.zip ./build/main.dist/*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: meg-${{ runner.os }}-x86_64
          path: |
            build/*.zip
