name: Executable Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: update gcc (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          aria2c -o win-gcc.7z https://github.com/niXman/mingw-builds-binaries/releases/download/13.1.0-rt_v11-rev1/x86_64-13.1.0-release-posix-seh-ucrt-rt_v11-rev1.7z
          7z x .\win-gcc.7z
          echo "${{ github.workspace }}/mingw64/bin" >> $GITHUB_PATH
          echo "${{ env }}"
          
      - name: update gcc (macOS)
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew install llvm
          
      - name: update gcc (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          
      - name: print gcc version
        run: |
          gcc -v
